### PR TITLE
cors configuration

### LINKED ISSUE #17: Fix cross origin only for development

### PR DESCRIPTION
**Pull request by HubertBalcerzak**
closes #17

### CODE REVIEW

**Comment by Kuboczoch** [comment]
Please add .env file with your configuration to the project. Every person that is currently working at this project will have to add another env, just because you are not doing it.

**Comment by HubertBalcerzak** [comment]
At least read the code before commenting. This configuration option has a default value, so nothing will break. More user friendly configuration is planned in the near future.

**Comment by Kuboczoch** [comment]
I can see that, but I'm talking about .env file, it's a more user-friendly solution for everyone and in there include default values.

**Comment by HubertBalcerzak** [comment]
sure, but that's out of the scope of this PR

**Pull request merged**
